apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - community-charts-helmrepo.yaml
  - home-assistant-helmrepo.yaml
  - longhorn-helmrepo.yaml
  - nginx-helmrepo.yaml
  - pihole-helmrepo.yaml
  - portainer-helmrepo.yaml
  - homepage-helmrepo.yaml
  - jetstack-helmrepo.yaml
