apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/cloudflared
  - cert-secret.sops.yaml
  - tunnel-secret.sops.yaml
configMapGenerator:
  - name: cloudflared-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
