tunnelSecrets:
  existingConfigJsonFileSecret:
    name: "cloudflared-credentials"
  existingPemFileSecret:
    name: "cloudflared-cert"

tunnelConfig:
  name: "homelab"

ingress:
  - hostname: hass.dtavana.dev
    service: http://nginx-system-nginx-ingress-nginx-controller.nginx-system.svc.cluster.local
  - hostname: home.dtavana.dev
    service: http://nginx-system-nginx-ingress-nginx-controller.nginx-system.svc.cluster.local
  - service: http_status:404
