persistentVolumeClaim:
  enabled: true
  size: 2Gi
  storageClass: longhorn
serviceWeb:
  type: LoadBalancer
serviceDns:
  type: LoadBalancer
podDnsConfig:
  enabled: false
dnsmasq:
  enableCustomDnsMasq: true
  customDnsEntries:
    - address=/internal.dtavana.dev/192.168.0.34
ingress:
  enabled: true
  ingressClassName: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/app-root: /admin
  hosts:
    - pihole.internal.dtavana.dev
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.internal.dtavana.dev

capabilities:
  add:
    - NET_ADMIN
