persistentVolumeClaim:
  enabled: true
  size: 2Gi
  storageClass: longhorn
serviceWeb:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.31
serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.30
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"
podDnsConfig:
  enabled: false
dnsmasq:
  enableCustomDnsMasq: true
  customDnsEntries:
    - address=/internal.dtavana.dev/192.168.0.34
ingress:
  enabled: true
  ingressClassName: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - pihole.internal.dtavana.dev
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.internal.dtavana.dev

capabilities:
  add:
    - NET_ADMIN
