apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/portainer
configMapGenerator:
  - name: portainer-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
