apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/homepage
configMapGenerator:
  - name: homepage-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
  - name: homepage-config
    namespace: homepage-system
    files:
      - settings.yaml=./settings.yaml
      - services.yaml=./services.yaml
      - widgets.yaml=./widgets.yaml
      - kubernetes.yaml=./kubernetes.yaml
