apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/homepage
  - config.yaml

configMapGenerator:
  - name: homepage-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
