apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base/home-assistant
configMapGenerator:
  - name: home-assistant-values
    namespace: flux-system
    files:
      - values.yaml=./values.yaml
