apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - pvc-matter-server.yaml
  - deployment-matter-server.yaml
  - service-matter-server.yaml

  - ../../../infrastructure/homelab/ghcr-creds

