apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/helm-sources
  - ./cert-manager
  - ./nginx
  - ./cloudflared
  - ./discord-alerts
  - ./longhorn
  - ./portainer
